[project]
name = "teachable"
version = "0.1.0"
description = "Download course content from Teachable platform"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
